"""remove unnecessary field from Set

Revision ID: 76b89d562ee9
Revises: 7a3ed23b8d0e
Create Date: 2026-01-27 19:19:01.840513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '76b89d562ee9'
down_revision: Union[str, Sequence[str], None] = '7a3ed23b8d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('set', 'total_cards')
    op.drop_column('set', 'secret_cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set', sa.Column('secret_cards', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('set', sa.Column('total_cards', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
