"""add item related tables

Revision ID: 7906845c291d
Revises: 82ed957acaef
Create Date: 2026-04-13 15:14:20.336082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7906845c291d'
down_revision: Union[str, Sequence[str], None] = '82ed957acaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('blister', 'booster', 'duopack', 'tripack', 'pokebox', 'coffret', 'half_display', 'display', 'ETB', 'bundle', 'mini_tin', 'art_set', name='itemtype'), nullable=False),
    sa.Column('retail_price', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_table('abstract_booster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('card_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'card_count', name='uq_card_number_booster')
    )
    op.create_table('item_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abstract_booster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['abstract_booster_id'], ['abstract_booster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_abstract_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('abstract_booster_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abstract_booster_id'], ['abstract_booster.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_exact_card_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booster_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('booster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booster_id'], ['booster.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_exact_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('booster_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booster_id'], ['booster.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('card', 'rarity',
               existing_type=mysql.ENUM('common', 'uncommon', 'rare', 'holographic', 'double_rare', 'alternative', 'ultra_rare', 'secret', 'alt_special_rare', 'hyper_rare', 'mega_hyper_rare', 'special_rare', 'shiny', 'rainbow_rare', 'gold_rare', 'double_shiny', 'promo', 'tech', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('card', 'type',
               existing_type=mysql.ENUM('pokemon', 'object', 'trainer', 'stadium', 'tool', 'energy', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('pokemon', 'object', 'trainer', 'stadium', 'energy', 'tool', name='cardtype'),
               existing_nullable=False)
    op.create_unique_constraint('uq_set_abbreviation', 'set', ['abbreviation'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_set_abbreviation', 'set', type_='unique')
    op.alter_column('card', 'type',
               existing_type=sa.Enum('pokemon', 'object', 'trainer', 'stadium', 'energy', 'tool', name='cardtype'),
               type_=mysql.ENUM('pokemon', 'object', 'trainer', 'stadium', 'tool', 'energy', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('card', 'rarity',
               existing_type=mysql.ENUM('common', 'uncommon', 'rare', 'holographic', 'double_rare', 'alternative', 'ultra_rare', 'secret', 'alt_special_rare', 'hyper_rare', 'mega_hyper_rare', 'special_rare', 'shiny', 'rainbow_rare', 'gold_rare', 'double_shiny', 'promo', 'tech', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.drop_table('item_exact_content')
    op.drop_table('booster_pokemon')
    op.drop_table('item_exact_card_content')
    op.drop_table('item_abstract_content')
    op.drop_table('booster')
    op.drop_table('item_pokemon')
    op.drop_table('abstract_booster')
    op.drop_table('user')
    op.drop_table('item')
    # ### end Alembic commands ###
