"""remove unnecessary field from Era

Revision ID: 7a3ed23b8d0e
Revises: d24fa9d3179d
Create Date: 2026-01-27 19:04:49.734370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a3ed23b8d0e'
down_revision: Union[str, Sequence[str], None] = 'd24fa9d3179d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('era', 'start_year')
    op.drop_column('era', 'publisher')
    op.drop_column('era', 'end_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('era', sa.Column('end_year', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('era', sa.Column('publisher', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('era', sa.Column('start_year', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
