"""Add path field to Pokemon

Revision ID: d24fa9d3179d
Revises: 39b2a840a5df
Create Date: 2025-11-19 17:54:47.165660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd24fa9d3179d'
down_revision: Union[str, Sequence[str], None] = '39b2a840a5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('image_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'image_path')
    # ### end Alembic commands ###
